# Generated by Django 3.1.7 on 2021-04-15 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('login', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-created'],
                'default_related_name': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=500)),
                ('zone', models.CharField(max_length=500)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='stats.building')),
            ],
            options={
                'ordering': ['-created'],
                'default_related_name': 'measurements',
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['created'], name='stats_build_created_d6325d_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['created'], name='stats_measu_created_29d5ea_idx'),
        ),
    ]
