# Generated by Django 3.2.7 on 2021-11-16 19:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                (
                    "recipients_copy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "recipients_blind_copy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=1000)),
                ("body", models.CharField(blank=True, max_length=1000)),
                ("body_link", models.CharField(blank=True, max_length=1000)),
                ("data", models.JSONField(null=True)),
                ("send_schedule", models.DateTimeField(auto_now_add=True)),
                ("attempts_number", models.PositiveSmallIntegerField(default=0)),
                ("sent_datetime", models.DateTimeField(blank=True, null=True)),
                ("sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sent", "send_schedule"],
                "default_related_name": "emails",
            },
        ),
    ]
