# Generated by Django 3.2.9 on 2021-12-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'default_related_name': 'emails', 'ordering': ['-created']},
        ),
    ]
